command_timeout = 2000

[java]
detect_folders = ["java", "bazel-zoolander"]
style = "bold green"
format = "[$symbol$version]($style) "

[python]
format = "[$symbol$version]($style) "
style = "bold green"
disabled = true

[ruby]
format = "[$symbol$version]($style) "

[nodejs]
format = ""

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "🌱 "
format = '[$symbol$branch]($style) '

[git_status]
# I don't care about untracked files or that there's a stash present.
untracked = ""
format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style) )'
modified = '*'
