command_timeout = 8000

[battery]
disabled = true

[java]
detect_folders = ["java", "bazel-zoolander"]
style = "bold green"
format = "[$symbol$version]($style) "

[python]
format = "[$symbol$version]($style) "
style = "bold green"
disabled = true

[ruby]
format = "[$symbol$version]($style) "
style = "bold green"

[nodejs]
format = ""

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "🌱 "
format = '[$symbol$branch]($style) '

[git_status]
untracked = ""
stashed = ""
conflicted = "🏳"
# disabled = true

# [env_var.1]
# variable="GSD_STATUS"
# format="[$env_value  ]()"
# [env_var.2a]
# variable="GSD_REMOTE"
# format="[$env_value ](#cccccc bold)"
# [env_var.2b]
# variable="GSD_REPO"
# format="[$env_value](white bold)"
# [env_var.3]
# variable="GSD_ON"
# format="[@$env_value](purple bold)"
# [env_var.4]
# variable="GSD_BRANCH_STATUS"
# format="[ $env_value ]()"
# [env_var.5]
# variable="GSD_NOT_REPO"
# format="[ ]()"